version: "3.7"
services:
  api:
    container_name: social_media_management
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8000:8000
    command: ["air", "-c", ".air.toml"]
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # - ./app/config/config.json:/app/config/config.json
      - ./:/app # Important to bind/mount your codebase dir to /app dir for live reload

  # # redis service can be seperate for replication
  redis:
    image: redis:6.0.9
    container_name: redis_service
    ports:
      - 6379:6379
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10