version: "3.7"
services:
  api:
    container_name: little_lives_api
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 9003:9001
    command: ["air", "-c", ".air.toml"]
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # - ./app/config/config.json:/app/config/config.json
      - ./:/app # Important to bind/mount your codebase dir to /app dir for live reload

  # Redis service can be seperate for replication
  redis:
    image: redis:6.0.9
    container_name: redis_service
    ports:
      - 6379:6379
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10

  # MongoDB service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  # Mongo Express service
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  minio:
    image: quay.io/minio/minio:RELEASE.2023-11-20T22-40-07Z
    command: server --console-address ":9001" /data1
    ports:
      - "9004:9000"
      - "9005:9001"
    environment:
      MINIO_ROOT_USER: Q3AM3UQ867SPQQA43P2F
      MINIO_ROOT_PASSWORD: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data1

volumes:
  dbdata:
  minio-data: